import Head from 'next/head'
// import Image from 'next/image'
import Table from '../../components/Table';

const Nav = (await import('app1/Nav')).default;

export default function Api() {
  return (
    <div>
        <Head>
            <title>API</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Nav href="/tokens" name="Tokens" />
        <h1>Tokens</h1>
        <Table />
    </div>
  )
}
